<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="urn:ServerWsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="myServer"
  targetNamespace="urn:ServerWsdl">
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ServerWsdl">
      <xsd:complexType name="getRequestType">
        <xsd:sequence>
          <xsd:element name="header" type="tns:standardheaderType" />
          <xsd:element name="body" type="tns:getRequestBodyType" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="getResultType">
        <xsd:sequence>
          <xsd:element name="result" type="tns:resultType" maxOccurs="1" minOccurs="0" />
          <xsd:element name="error" type="tns:errorType" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="standardheaderType">
        <xsd:sequence>
          <xsd:element name="applicationversionnr" type="xsd:string" maxOccurs="1" minOccurs="1" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="getRequestBodyType">
        <xsd:sequence>
          <xsd:element name="transactioncode" type="xsd:string" maxOccurs="1" minOccurs="1" />
          <xsd:element name="languageisocode" type="xsd:string" maxOccurs="1" minOccurs="1" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="disclosureinformationType">
        <xsd:sequence>
          <xsd:element name="companyname" type="xsd:string" maxOccurs="1" minOccurs="0" />
          <xsd:element
            name="street" type="xsd:string" maxOccurs="1" minOccurs="0" />
          <xsd:element
            name="countryisocode" type="xsd:string" maxOccurs="1" minOccurs="0" />
          <xsd:element
            name="city" type="xsd:string" maxOccurs="1" minOccurs="0" />
          <xsd:element name="postcode"
            type="xsd:string" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="clientinformationType">
        <xsd:sequence>
          <xsd:element name="fieldname" type="xsd:string" maxOccurs="1" minOccurs="0" />
          <xsd:element name="fieldvalue" type="xsd:string" maxOccurs="1" minOccurs="0" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="resultType">
        <xsd:sequence>
          <xsd:element name="transactioncode" type="xsd:string" />
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="errorType">
        <xsd:sequence>
          <xsd:element name="errorcode" type="xsd:string" />
          <xsd:element name="errortext" type="xsd:string" />
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="getRequest">
    <wsdl:part name="getRequest" type="tns:getRequestType" />
  </wsdl:message>
  <wsdl:message name="getResponse">
    <wsdl:part name="getResponse" type="tns:getResultType" />
  </wsdl:message>
  <wsdl:portType name="myServer">
    <wsdl:operation name="get">
      <wsdl:input message="tns:getRequest" />
      <wsdl:output message="tns:getResponse" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="myServerSOAP" type="tns:myServer">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="get">
      <soap:operation soapAction="urn:ServerWsdl/get" />
      <wsdl:input>
        <soap:body namespace="urn:ServerWsdl" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="urn:ServerWsdl" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="myServer">
    <wsdl:port binding="tns:myServerSOAP" name="myServerSOAP">
      <soap:address
        location="https://some.server.de/myServer.php" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
